src/Entity/Productos.php
<?php

namespace App\Entity;

use App\Repository\ProductosRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductosRepository::class)
 */
class Productos
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $fecha;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cod_referencia;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombre;

    /**
     * @ORM\Column(type="float")
     */
    private $precio;

    /**
     * @ORM\Column(type="float")
     */
    private $peso;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $descripcion;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ean;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $imagen;

    /**
     * @ORM\Column(type="integer")
     */
    private $stock;

    /**
     * @ORM\ManyToOne(targetEntity=Marcas::class, inversedBy="productos")
     */
    private $id_marca;

    /**
     * @ORM\ManyToOne(targetEntity=Categorias::class, inversedBy="productos")
     */
    private $id_categoria;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $url;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titulo;

    /**
     * @ORM\OneToMany(targetEntity=OrderItem::class, mappedBy="product")
     */
    private $orderItems;

    public function __construct()
    {
        $this->orderItems = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFecha(): ?\DateTimeInterface
    {

        return $this->fecha;
    }

    public function setFecha(?\DateTimeInterface $fecha): self
    {
        $this->fecha = $fecha;

        return $this;
    }

    public function getCodReferencia(): ?string
    {
        return $this->cod_referencia;
    }

    public function setCodReferencia(string $cod_referencia): self
    {
        $this->cod_referencia = $cod_referencia;

        return $this;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getPrecio(): ?float
    {
        return $this->precio;
    }

    public function setPrecio(float $precio): self
    {
        $this->precio = $precio;

        return $this;
    }

    public function getPeso(): ?float
    {
        return $this->peso;
    }

    public function setPeso(float $peso): self
    {
        $this->peso = $peso;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->descripcion;
    }

    public function setDescripcion(?string $descripcion): self
    {
        $this->descripcion = $descripcion;

        return $this;
    }

    public function getEan(): ?string
    {
        return $this->ean;
    }

    public function setEan(string $ean): self
    {
        $this->ean = $ean;

        return $this;
    }

    public function getImagen(): ?string
    {
        return $this->imagen;
    }

    public function setImagen(string $imagen): self
    {
        $this->imagen = $imagen;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): self
    {
        $this->stock = $stock;

        return $this;
    }

    public function getIdMarca(): ?Marcas
    {
        return $this->id_marca;
    }

    public function setIdMarca(?Marcas $id_marca): self
    {
        $this->id_marca = $id_marca;

        return $this;
    }

    public function getIdCategoria(): ?Categorias
    {
        return $this->id_categoria;
    }

    public function setIdCategoria(?Categorias $id_categoria): self
    {
        $this->id_categoria = $id_categoria;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getTitulo(): ?string
    {
        return $this->titulo;
    }

    public function setTitulo(string $titulo): self
    {
        $this->titulo = $titulo;

        return $this;
    }

    /**
     * @return Collection|OrderItem[]
     */
    public function getOrderItems(): Collection
    {
        return $this->orderItems;
    }

    public function addOrderItem(OrderItem $orderItem): self
    {
        if (!$this->orderItems->contains($orderItem)) {
            $this->orderItems[] = $orderItem;
            $orderItem->setProduct($this);
        }

        return $this;
    }

    public function removeOrderItem(OrderItem $orderItem): self
    {
        if ($this->orderItems->removeElement($orderItem)) {
            // set the owning side to null (unless already changed)
            if ($orderItem->getProduct() === $this) {
                $orderItem->setProduct(null);
            }
        }

        return $this;
    }




}

src/Form/ProductosType.php
<?php

namespace App\Form;

use App\Entity\Productos;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductosType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('fecha', HiddenType::class)
            ->add('cod_referencia')
            ->add('nombre')
            ->add('precio')
            ->add('peso')
            ->add('descripcion')
            ->add('ean')
            ->add('imagen',FileType::class, [
                'mapped' => false
            ])
            ->add('stock')
            ->add('id_marca', CollectionType::class, [
                'entry_type'=>MarcasABSType::class,
                'entry_options' => ['label' => false]])

            ->add('id_categoria', CollectionType::class, [
                'entry_type'=>CategoriasABSType::class,
                'entry_options' => ['label' => false]])

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Productos::class,
        ]);
    }
}

src/Controller/ProductosController.php
<?php

namespace App\Controller;

use App\Entity\Categorias;
use App\Entity\Marcas;
use App\Entity\Productos;
use App\Form\AddToCartType;
use App\Form\ProductosModificarType;
use App\Form\ProductosType;
use App\Manager\CartManager;
use App\Repository\ProductosRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;
/**
 * @Route("/productos")
 */
class ProductosController extends AbstractController
{
    /**
     * @Route("/", name="productos_index", methods={"GET"})
     */
    public function index(ProductosRepository $productosRepository, Request $request, PaginatorInterface $paginator): Response
    {
        $products = $productosRepository->findAll();
        $allAppointmentsQuery = $productosRepository->createQueryBuilder('p')
            ->where('p.id != :id')
            ->setParameter('id', 'null')
            ->getQuery();
        $products = $paginator->paginate(
            $allAppointmentsQuery,
            // Define the page parameter
            $request->query->getInt('page', 1),
            // Items per page
            16
        );
        return $this->render('productos/index.html.twig', [
            'productos' => $products,
        ]);
    }

    /**
     * @Route("/new", name="productos_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $producto = new Productos();


        $form = $this->createForm(ProductosType::class, $producto);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $uploadedFile */
            $uploadedFile = $form['imagen']->getData();

            if ($uploadedFile) {
                $destination = $this->getParameter('kernel.project_dir').'/public/uploads/productos';
                $originalFilename = pathinfo($uploadedFile->getClientOriginalName(), PATHINFO_BASENAME);

                $uploadedFile->move(
                    $destination,
                    $originalFilename
                );
                $producto->setImagen($originalFilename);
                $producto->setFecha(new \DateTime("now"));
            }
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($producto);
            $entityManager->flush();

            return $this->redirectToRoute('productos_index');
        }

        return $this->render('productos/new.html.twig', [
            'producto' => $producto,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="productos_show", methods={"GET","POST"})
     * @param Productos $producto
     * @return Response
     */
    public function show(Productos $producto): Response
    {
        return $this->render('productos/show.html.twig', [
            'producto' => $producto,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="productos_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Productos $producto): Response
    {
        $form = $this->createForm(ProductosModificarType::class, $producto);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('productos_index');
        }

        return $this->render('productos/edit.html.twig', [
            'producto' => $producto,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="productos_delete", methods={"POST"})
     */
    public function delete(Request $request, Productos $producto): Response
    {
        if ($this->isCsrfTokenValid('delete'.$producto->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($producto);
            $entityManager->flush();
        }

        return $this->redirectToRoute('productos_index');
    }

    /**
     * @Route("/view/{id}", name="product.detail")
     */
    public function detail(Productos $producto, Request $request, CartManager $cartManager)
    {
        $form = $this->createForm(AddToCartType::class);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $item = $form->getData();
            $item->setProduct($producto);

            $cart = $cartManager->getCurrentCart();
            $cart
                ->addItem($item)
                ->setUpdatedAt(new \DateTime());

            $cartManager->save($cart);

            return $this->redirectToRoute('product.detail', ['id' => $producto->getId()]);
        }

        return $this->render('productos/detail.html.twig', [
            'producto' => $producto,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/{id}/productos", name="productos_categoria",  methods={"GET"})
     */
    public function prodCategoria(Categorias $categoria, Request $request, PaginatorInterface $paginator, ProductosRepository $productoRepository) : Response{


        $allAppointmentsQuery = $productoRepository->getProductosByCat($categoria->getId());
        $products = $paginator->paginate(
            $allAppointmentsQuery,
            // Define the page parameter
            $request->query->getInt('page', 1),
            // Items per page
            16
        );
        return $this->render('categorias/product_colection.html.twig', [
            'categorias' => $products,
        ]);
    }



    /**
     * @Route("/{id}/productos-marcas", name="productos_marca",  methods={"GET"})
     */
    public function prodMarca(Marcas $categoria, Request $request, PaginatorInterface $paginator, ProductosRepository $productoRepository) : Response{


        $allAppointmentsQuery = $productoRepository->getProductosByMarc($categoria->getId());
        $products = $paginator->paginate(
            $allAppointmentsQuery,
            // Define the page parameter
            $request->query->getInt('page', 1),
            // Items per page
            16
        );
        return $this->render('marcas/product_colection.html.twig', [
            'categorias' => $products,
        ]);
    }


}

templates/productos/_delete_form.html.twig
<form method="post" action="{{ path('productos_delete', {'id': producto.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ producto.id) }}">
    <button class="btn">Eliminar</button>
</form>

templates/productos/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/productos/carga_masiva.html.twig
{% include 'navbar.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
      .btn{

            color: #ffffff;
            padding: 0.8rem;
            font-size: 14px;
            text-transform: uppercase;
            border-radius: 4px;
            font-weight: 400;

            width: 120px;
            cursor: pointer;
            border: 1px solid rgba(255, 255, 255, 0.2);
            background: linear-gradient(to bottom left, #f6d148 40%, #ffc89e 100%);
            bottom: 0;
        }
    </style>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

{% endblock %}
{% block body %}
<div class="container mt-4">
    <h3 class="text-center">Carga Masiva</h3>
</br>
    </br>
    </br>
    <div class="row">
        <div class="form-group col-md-6 align-self-center">
    {{ form_start(form) }}
            <button class="btn">{{ button_label|default('Subir') }}</button>
    {{ form_end(form) }}
        </br>

        </div>
        <div class="form-group col-md-6 ">
        <p>- Si quieres ver un ejemplo de subida, puedes descargarlo desde aquí</p>
           <p>- Sino suba el fichero directamente</p>
            <a class="btn "href="{{asset('uploads/CSV/pruebaBBDD_tfg.csv')}}">Bajar demo</a>

        </div>
    </div>

</div>

{% endblock %}

{% include 'footer.html.twig' %}

templates/productos/detail.html.twig
{% include 'navbar.html.twig' %}
 {% block stylesheets %}
     <link href="{{ asset('assets/css/product-detail.css') }}" type="text/css" rel="stylesheet" />
     <style>

         .search-button {

             height: 40px;
         }
         .form-control{
             background-color: white;
             border: 1px ;
         }
     </style>
 {% endblock %}
{% block body %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <div class="go-back" style="max-width: 1000px;
    margin: 0 auto; margin-top: 20px">
        <a style=" text-decoration: none; color: #f6d148" href="{{ path('productos_index') }}">Volver</a>
    </div>

<div class="container" >

    <div class="div-left">
        <div class="div-img">
            <img src="{{ producto.imagen }}"></td>
        </div>
    </div>
    <div class="div-rigth">
        <h2>{{ producto.titulo }}</h2>
        <span class="price">{{ producto.precio }} €</span>
        <p class="description">{{ producto.descripcion }}</p>
        {{ form_start(form, {'attr': {'class': 'mt-4 p-4 bg-light'}}) }}
        <div class="form-group">
            {{ form_label(form.cantidad) }}
            {{ form_widget(form.cantidad, {
                'attr': {
                    'class': 'form-control ' ~ (form.cantidad.vars.valid ? '' : 'is-invalid')
                }
            }) }}
            <div class="invalid-feedback">
                {{ form_errors(form.cantidad) }}
            </div>
        </div>

        {{ form_end(form) }}
    </div>
</div>

{% endblock %}

{% block javascripts %}
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script>
    $('form[name="add_to_cart"]').submit(function() {
        swal({
            title: "Añadido correctamente!",
            text: "puedes seguir comprando o dirigirte al carrito",
            icon: "success",
            button: "Continuar",
            closeOnConfirm: true,
            timer: 60000

        });

    });
</script>

{% endblock %}

templates/productos/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Productos{% endblock %}

{% block body %}
    <h1>Edit Productos</h1>

    {{ include('productos/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('productos_index') }}">back to list</a>

    {{ include('productos/_delete_form.html.twig') }}
{% endblock %}

templates/productos/index.html.twig
{% include 'navbar.html.twig' %}

  {% block stylesheets %}
      <link href="{{ asset('assets/css/cards.css') }}" type="text/css" rel="stylesheet" />
      <style>

          .search-button {

              height: 40px;
          }
      </style>
  {% endblock %}
{% block body %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <div class="main">
        <h1>Productos</h1>
        <ul class="cards">

        {% for producto in productos %}
            {% if producto.stock > 0 %}
            <li class="cards_item">
                <div class="card">
                    <div class="card_image"><img src="{{ producto.imagen }}"></div>
                    <div class="card_content">
                        <h2 class="card_title">{{ producto.nombre }}</h2>
                        <p class="card_text">{{ producto.precio }} €</p>
                        <button class="btn card_btn"><a href="{{ path('product.detail', {'id': producto.id}) }}">Ver producto</a></button>
                    </div>
                </div>
            </li>
            {% endif %}
        {% else %}
            <p>No hay resultados</p>
        {% endfor %}
            </ul>
        <div class="navigation">
            {{ knp_pagination_render(productos) }}
        </div>
        </div>



{% endblock %}

  {% include 'footer.html.twig' %}

templates/productos/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Productos{% endblock %}

{% block body %}
    <h1>Create new Productos</h1>

    {{ include('productos/_form.html.twig') }}

    <a href="{{ path('productos_index') }}">back to list</a>
{% endblock %}

templates/productos/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Productos{% endblock %}

{% block body %}
    <h1>Productos</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ producto.id }}</td>
            </tr>
            <tr>
                <th>Fecha</th>
                <td>{{ producto.fecha ? producto.fecha|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Cod_referencia</th>
                <td>{{ producto.codReferencia }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ producto.nombre }}</td>
            </tr>
            <tr>
                <th>Precio</th>
                <td>{{ producto.precio }}</td>
            </tr>
            <tr>
                <th>Peso</th>
                <td>{{ producto.peso }}</td>
            </tr>
            <tr>
                <th>Descripcion</th>
                <td>{{ producto.descripcion }}</td>
            </tr>
            <tr>
                <th>Ean</th>
                <td>{{ producto.ean }}</td>
            </tr>
            <tr>
                <th>Imagen</th>
                <td><img style="width: 200px" src="{{ producto.imagen }}"></td>
            </tr>
            <tr>
                <th>Stock</th>
                <td>{{ producto.stock }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('productos_index') }}">Volver a la lista</a>

    <a href="{{ path('productos_edit', {'id': producto.id}) }}">Editar</a>

    {{ include('productos/_delete_form.html.twig') }}
{% endblock %}