src/Entity/Pedidos.php
<?php

namespace App\Entity;

use App\Repository\PedidosRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PedidosRepository::class)
 */
class Pedidos
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $fecha;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $num_pedido;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cod_pedido;

    /**
     * @ORM\Column(type="float")
     */
    private $precio;

    /**
     * @ORM\Column(type="array")
     */
    private $array_productos = [];

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="marcas")
     */
    private $id_cliente;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFecha(): ?\DateTimeInterface
    {
        return $this->fecha;
    }

    public function setFecha(?\DateTimeInterface $fecha): self
    {
        $this->fecha = $fecha;

        return $this;
    }

    public function getNumPedido(): ?string
    {
        return $this->num_pedido;
    }

    public function setNumPedido(string $num_pedido): self
    {
        $this->num_pedido = $num_pedido;

        return $this;
    }

    public function getCodPedido(): ?string
    {
        return $this->cod_pedido;
    }

    public function setCodPedido(string $cod_pedido): self
    {
        $this->cod_pedido = $cod_pedido;

        return $this;
    }

    public function getPrecio(): ?float
    {
        return $this->precio;
    }

    public function setPrecio(float $precio): self
    {
        $this->precio = $precio;

        return $this;
    }

    public function getArrayProductos(): ?array
    {
        return $this->array_productos;
    }

    public function setArrayProductos(array $array_productos): self
    {
        $this->array_productos = $array_productos;

        return $this;
    }

    public function getIdCliente(): ?User
    {
        return $this->id_cliente;
    }

    public function setIdCliente(?User $id_cliente): self
    {
        $this->id_cliente = $id_cliente;

        return $this;
    }
}

src/Form/PedidosType.php
<?php

namespace App\Form;

use App\Entity\Pedidos;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PedidosType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('fecha')
            ->add('num_pedido')
            ->add('cod_pedido')
            ->add('precio')
            ->add('array_productos')
            ->add('id_cliente')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Pedidos::class,
        ]);
    }
}

src/Controller/PedidosController.php
<?php

namespace App\Controller;

use App\Entity\Pedidos;
use App\Form\PedidosType;
use App\Repository\PedidosRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/marcas")
 */
class PedidosController extends AbstractController
{
    /**
     * @Route("/", name="pedidos_index", methods={"GET"})
     */
    public function index(PedidosRepository $pedidosRepository): Response
    {
        return $this->render('marcas/index.html.twig', [
            'marcas' => $pedidosRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="pedidos_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $pedido = new Pedidos();
        $form = $this->createForm(PedidosType::class, $pedido);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

                $pedido->setFecha(new \DateTime("now"));

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($pedido);
            $entityManager->flush();

            return $this->redirectToRoute('pedidos_index');
        }

        return $this->render('marcas/new.html.twig', [
            'pedido' => $pedido,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="pedidos_show", methods={"GET"})
     */
    public function show(Pedidos $pedido): Response
    {
        return $this->render('marcas/show.html.twig', [
            'pedido' => $pedido,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="pedidos_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Pedidos $pedido): Response
    {
        $form = $this->createForm(PedidosType::class, $pedido);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('pedidos_index');
        }

        return $this->render('marcas/edit.html.twig', [
            'pedido' => $pedido,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="pedidos_delete", methods={"POST"})
     */
    public function delete(Request $request, Pedidos $pedido): Response
    {
        if ($this->isCsrfTokenValid('delete'.$pedido->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($pedido);
            $entityManager->flush();
        }

        return $this->redirectToRoute('pedidos_index');
    }
}

templates/pedidos/_delete_form.html.twig
<form method="post" action="{{ path('pedidos_delete', {'id': pedido.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ pedido.id) }}">
    <button class="btn">Delete</button>
</form>

templates/pedidos/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Guardar') }}</button>
{{ form_end(form) }}

templates/pedidos/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Pedidos{% endblock %}

{% block body %}
    <h1>Edit Pedidos</h1>

    {{ include('marcas/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('pedidos_index') }}">back to list</a>

    {{ include('marcas/_delete_form.html.twig') }}
{% endblock %}

templates/pedidos/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pedidos index{% endblock %}

{% block body %}
    <h1>Pedidos index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Fecha</th>
                <th>Num_pedido</th>
                <th>Cod_pedido</th>
                <th>Precio</th>
                <th>Array_productos</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for pedido in pedidos %}
            <tr>
                <td>{{ pedido.id }}</td>
                <td>{{ pedido.fecha ? pedido.fecha|date('Y-m-d') : '' }}</td>
                <td>{{ pedido.numPedido }}</td>
                <td>{{ pedido.codPedido }}</td>
                <td>{{ pedido.precio }}</td>
                <td>{{ pedido.arrayProductos ? pedido.arrayProductos|join(', ') : '' }}</td>
                <td>
                    <a href="{{ path('pedidos_show', {'id': pedido.id}) }}">show</a>
                    <a href="{{ path('pedidos_edit', {'id': pedido.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('pedidos_new') }}">Create new</a>
{% endblock %}

templates/pedidos/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Pedidos{% endblock %}

{% block body %}
    <h1>Create new Pedidos</h1>

    {{ include('marcas/_form.html.twig') }}

    <a href="{{ path('pedidos_index') }}">back to list</a>
{% endblock %}

templates/pedidos/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pedidos{% endblock %}

{% block body %}
    <h1>Pedidos</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ pedido.id }}</td>
            </tr>
            <tr>
                <th>Fecha</th>
                <td>{{ pedido.fecha ? pedido.fecha|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Num_pedido</th>
                <td>{{ pedido.numPedido }}</td>
            </tr>
            <tr>
                <th>Cod_pedido</th>
                <td>{{ pedido.codPedido }}</td>
            </tr>
            <tr>
                <th>Precio</th>
                <td>{{ pedido.precio }}</td>
            </tr>
            <tr>
                <th>Array_productos</th>
                <td>{{ pedido.arrayProductos ? pedido.arrayProductos|join(', ') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('pedidos_index') }}">back to list</a>

    <a href="{{ path('pedidos_edit', {'id': pedido.id}) }}">edit</a>

    {{ include('marcas/_delete_form.html.twig') }}
{% endblock %}