src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use SpecShaper\EncryptBundle\Annotations\Encrypted;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Encrypted
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Encrypted
     */
    private $empresa;

    /**
     * @ORM\Column(type="string", length=50)
     * @Encrypted
     */
    private $telefono;

    /**
     * @ORM\Column(type="string", length=255)
     * @Encrypted
     */
    private $nombre;

    /**
     * @ORM\Column(type="string", length=255)
     * @Encrypted
     */
    private $cod_cliente;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Encrypted
     */
    private $direccion;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Encrypted
     */
    private $provincia;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Encrypted
     */
    private $ciudad;

    /**
     * @ORM\OneToMany(targetEntity=Pedidos::class, mappedBy="id_cliente")
     */
    private $pedidos;

    /**
     * @ORM\OneToMany(targetEntity=Order::class, mappedBy="id_cliente")
     */
    private $orders;

    public function __construct()
    {
        $this->pedidos = new ArrayCollection();
        $this->orders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        global $kernel;
        if (method_exists($kernel, 'getKernel'))
            $kernel = $kernel->getKernel();

        $this->password = $kernel->getContainer()->get('security.password_encoder')->encodePassword($this, $password);
        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getEmpresa(): ?string
    {
        return $this->empresa;
    }

    public function setEmpresa(?string $empresa): self
    {
        $this->empresa = $empresa;

        return $this;
    }

    public function getTelefono(): ?string
    {
        return $this->telefono;
    }

    public function setTelefono(string $telefono): self
    {
        $this->telefono = $telefono;

        return $this;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getCodCliente(): ?string
    {
        return $this->cod_cliente;
    }

    public function setCodCliente(string $cod_cliente): self
    {
        $this->cod_cliente = $cod_cliente;

        return $this;
    }

    public function getDireccion(): ?string
    {
        return $this->direccion;
    }

    public function setDireccion(?string $direccion): self
    {
        $this->direccion = $direccion;

        return $this;
    }

    public function getProvincia(): ?string
    {
        return $this->provincia;
    }

    public function setProvincia(?string $provincia): self
    {
        $this->provincia = $provincia;

        return $this;
    }

    public function getCiudad(): ?string
    {
        return $this->ciudad;
    }

    public function setCiudad(?string $ciudad): self
    {
        $this->ciudad = $ciudad;

        return $this;
    }

    /**
     * @return Collection|Pedidos[]
     */
    public function getPedidos(): Collection
    {
        return $this->pedidos;
    }

    public function addPedido(Pedidos $pedido): self
    {
        if (!$this->pedidos->contains($pedido)) {
            $this->pedidos[] = $pedido;
            $pedido->setIdCliente($this);
        }

        return $this;
    }

    public function removePedido(Pedidos $pedido): self
    {
        if ($this->pedidos->removeElement($pedido)) {
            // set the owning side to null (unless already changed)
            if ($pedido->getIdCliente() === $this) {
                $pedido->setIdCliente(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Order[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->setIdCliente($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getIdCliente() === $this) {
                $order->setIdCliente(null);
            }
        }

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder

            ->add('email')
            ->add('empresa')
            ->add('telefono')
            ->add('nombre')
            ->add('cod_cliente')
            ->add('direccion')
            ->add('provincia')
            ->add('ciudad')

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/User/DashboardUserController.php
<?php
namespace App\Controller\User;



use App\Entity\Order;
use App\Entity\OrderItem;
use App\Entity\Productos;
use App\Entity\User;
use App\Repository\OrderItemRepository;
use App\Repository\UserRepository;
use App\Security\Encryptor;
use App\Storage\CartSessionStorage;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityManager;
use Knp\Bundle\SnappyBundle\Snappy\Response\PdfResponse;
use Knp\Snappy\Pdf;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;
use SpecShaper\EncryptBundle\Encryptors\EncryptorInterface;


class DashboardUserController extends AbstractController
{

    private $userRepository;
    private $cartSessionStorage;
    private $entityManager;
    private $security;
    //private $encryptor;

    /**
     * CartManager constructor.
     *
     * @param CartSessionStorage $cartStorage
     * @param EntityManagerInterface $entityManager
     * @param UserRepository $userRepository
     * @param Security $security
     */
    public function __construct(
        CartSessionStorage $cartStorage,
        EntityManagerInterface $entityManager,
        UserRepository $userRepository,
        Security $security
        //Encryptor $encryptor
    ) {
        $this->cartSessionStorage = $cartStorage;
        $this->entityManager = $entityManager;
        $this->userRepository = $userRepository;
        $this->security = $security;
       // $this->encryptor = $encryptor;
    }

    /**
     * @Route("/userPanel", name="userPanel")
     */

    public function getCurrUser()
    {
        $idUser = $this->userRepository->findOneBy(['id' => $this->security->getUser()->getId()]);
        $user = $this->entityManager->getRepository(User::class)->findBy([
            'id' =>$idUser]);



        $id = $user[0]->getId();

        return $this->redirectToRoute('user_edit',['id'=>$id]);

    }

    /**
         * @Route("/userPanelPedidos", name="userPanelPedidos")
     */

    public function getCurrUserOrders()
    {
        $idUser = $this->userRepository->findOneBy(['id' => $this->security->getUser()->getId()]);
        $user = $this->entityManager->getRepository(User::class)->findBy([
            'id' =>$idUser]);
        $id = $user[0]->getId();


        $order = $this->getDoctrine()
            ->getRepository(Order::class)
            ->findBy(['id_cliente'=> $id]);

       /* foreach ($order as $orders)
        $idOrder = $orders->getId();
        dump($idOrder);
        $order = $this->getDoctrine()
            ->getRepository(OrderItem::class)
            ->findBy(['order_ref'=> $id]);

       foreach ($idOrder as $idO){
            $order = $this->getDoctrine()
                ->getRepository(OrderItem::class)
                ->findBy(['order_ref'=> $idO]);
        }*/
       return $this->render('user/user_orders.html.twig', [
            'order' => $order,

        ]);
    }
    /**
     * @Route("detallesPedido/{id}", name="order_details", methods={"POST","GET"})
     */
    public function viewOrderDetails(Request $request){
        $idOrder = $request->get('id');
        $order = $this->getDoctrine()
            ->getRepository(OrderItem::class)
            ->findBy(['orderRef'=> $idOrder]);

    $total = 0;
        foreach ($order as $orTot){
            $total+= $orTot->getTotal();
        }

       /* $cont = 0;
        dump($order);
        $productsArray = Array();
        foreach ($order as $or){

            $order[$cont]->getProduct()->getId();

            $producto = $this->getDoctrine()
                ->getRepository(Productos::class)
                ->findBy(['id'=> $order[$cont]->getProduct()->getId()]);
            array_push($productsArray,$producto);

            $cont++;
        }
        dump($productsArray);
        /*$order = $this->getDoctrine()
            ->getRepository(OrderItem::class)
            ->findBy(['orderRef'=> $request->get('id')]);
        foreach ($order as $a){
            dump($a->getProduct());

*/
       return $this->render('user/order_detail.html.twig', $data = [
            'order' => $order,
            'total' => $total
        ]);  }



}
?>

src/Controller/User/UserOrderCrudController.php
<?php

namespace App\Controller\User;

use App\Entity\Order;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;

class UserOrderCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Order::class;
    }

    /*
    public function configureFields(string $pageName): iterable
    {
        return [
            IdField::new('id'),
            TextField::new('title'),
            TextEditorField::new('description'),
        ];
    }
    */
}

src/Controller/User/UserUserCrudController.php
<?php

namespace App\Controller\User;

use App\Entity\User;
use App\Repository\UserRepository;
use App\Storage\CartSessionStorage;
use Doctrine\ORM\EntityManagerInterface;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Orm\EntityRepository;
use Symfony\Component\Security\Core\Security;

class UserUserCrudController extends AbstractCrudController
{
    private $userRepository;
    private $cartSessionStorage;
    private $entityManager;
    private $security;

    /**
     * CartManager constructor.
     *
     * @param CartSessionStorage $cartStorage
     * @param EntityManagerInterface $entityManager
     * @param UserRepository $userRepository
     * @param Security $security
     */
    public function __construct(
        CartSessionStorage $cartStorage,
        EntityManagerInterface $entityManager,
        UserRepository $userRepository,
        Security $security

    ) {
        $this->cartSessionStorage = $cartStorage;
        $this->entityManager = $entityManager;
        $this->userRepository = $userRepository;
        $this->security = $security;
    }
    public static function getEntityFqcn(): string
    {
        return User::class;
    }



}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\OrderItem;
use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use App\Security\Encryptor;
use Knp\Bundle\SnappyBundle\Snappy\Response\PdfResponse;
use Knp\Snappy\Pdf;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/user")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="user_index", methods={"GET"})
     */
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="user_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {

        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="user_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, User $user): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $id = $request->get('id');
            return $this->redirectToRoute('user_edit',['id'=>$id]);
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_delete", methods={"POST"})
     */
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_index');
    }




}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Eliminar</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Guardar') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% include 'navbar.html.twig' %}
{% block stylesheets %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        form .btn{

            color: #ffffff;
            padding: 0.8rem;
            font-size: 14px;
            text-transform: uppercase;
            border-radius: 4px;
            font-weight: 400;

            width: 120px;
            cursor: pointer;
            border: 1px solid rgba(255, 255, 255, 0.2);
            background: linear-gradient(to bottom left, #f6d148 40%, #ffc89e 100%);
            bottom: 0;
        }

    </style>
{% endblock %}
{% block body %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<div class="container mt-4">
    <h3 class="text-center">Modificar Usuario</h3>
    <br><br>
        {{ form_start(form) }}
        <div class="form-row">
            <div class="form-group col-md-6">
                {{ form_label(form.email) }}
                {{ form_errors(form.email) }}
                {{ form_widget(form.email) }}
            </div>
            <div class="form-group col-md-6">
                {{ form_label(form.nombre) }}
                {{ form_errors(form.nombre) }}
                {{ form_widget(form.nombre) }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                {{ form_label(form.empresa) }}
                {{ form_errors(form.empresa) }}
                {{ form_widget(form.empresa) }}
            </div>
            <div class="form-group col-md-6">

                {{ form_label(form.cod_cliente) }}
                {{ form_errors(form.cod_cliente) }}
                {{ form_widget(form.cod_cliente) }}
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                {{ form_label(form.provincia) }}
                {{ form_errors(form.provincia) }}
                {{ form_widget(form.provincia) }}
            </div>
            <div class="form-group col-md-6">

                {{ form_label(form.ciudad) }}
                {{ form_errors(form.ciudad) }}
                {{ form_widget(form.ciudad)}}
            </div>
        </div>

        <div class="form-group">

            {{ form_label(form.direccion) }}
            {{ form_errors(form.direccion) }}
            {{ form_widget(form.direccion) }}

        </div>
        <div class="form-group">


            {{ form_label(form.telefono) }}
            {{ form_errors(form.telefono) }}
            {{ form_widget(form.telefono) }}
        </div>








<div class="form-row">
    <div class="btn-group" role="group" aria-label="Basic example">
    <div class="form-group col-md-6">

    {{ include('user/_form.html.twig', {'button_label': 'Actualizar'}) }}

    </div>

    <div class="form-group col-md-6">
    {{ include('user/_delete_form.html.twig',  {'button_label': 'Eliminar'})  }}

    </div>
    </div>
</div>
        {{ form_end(form) }}
</div>
{% endblock %}

{% include 'footer.html.twig' %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <h1>User index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Email</th>
                <th>Empresa</th>
                <th>Telefono</th>
                <th>Nombre</th>
                <th>Cod_cliente</th>
                <th>Direccion</th>
                <th>Provincia</th>
                <th>Ciudad</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.empresa }}</td>
                <td>{{ user.telefono }}</td>
                <td>{{ user.nombre }}</td>
                <td>{{ user.codCliente }}</td>
                <td>{{ user.direccion }}</td>
                <td>{{ user.provincia }}</td>
                <td>{{ user.ciudad }}</td>
                <td>
                    <a href="{{ path('user_show', {'id': user.id}) }}">show</a>
                    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_register') }}">Create new</a>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Create new User</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('user_index') }}">back to list</a>
{% endblock %}

templates/user/order_detail.html.twig
{% include 'navbar.html.twig' %}


{% block body %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        .table-container{
            width: auto;
            margin-top: 40px;
            overflow-x:auto;

        }
        .table-container h1{
            text-align: center;
        }

        .table-container p{
            float: right;
        }
        .container{

            text-align: center;
            margin: auto;
            width:auto;


        }
        .container th{
            padding: 50px;
        }
        .table-total{
            margin: auto;
            width: 200px;
            margin-top: 40px;
        font-size: 1.25rem;
        }


        img{
            width: 80px;
        }
    </style>
    <div class="table-container">
        <h1>Detalles del pedido</h1>
    <table class="container">
        <thead>
        <tr>
            <th>Cantidad</th>
            <th>Producto</th>
            <th>Coste Unidad</th>
            <th>Imagen</th>
            <th>Precio</th>

        </tr>
        </thead>
        <tbody>
        {% for orders in order %}
    <tr>
                <td>{{ orders.cantidad }}</td>

        <td>{{ orders.product.nombre }}</td>
        <td>{{ orders.product.precio }} € </td>
        <td><img src="{{ orders.product.imagen }}"></td>
        <td>{{ orders.getTotal() }} €</td>
    </tr>

        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}



        </tbody>

    </table>
    <div class="table-total">
        <p>Total {{ total }} €</p>
    </div>
    </div>
{% endblock %}
{% include 'footer.html.twig' %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <h1>User</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
            <tr>
                <th>Empresa</th>
                <td>{{ user.empresa }}</td>
            </tr>
            <tr>
                <th>Telefono</th>
                <td>{{ user.telefono }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ user.nombre }}</td>
            </tr>
            <tr>
                <th>Cod_cliente</th>
                <td>{{ user.codCliente }}</td>
            </tr>
            <tr>
                <th>Direccion</th>
                <td>{{ user.direccion }}</td>
            </tr>
            <tr>
                <th>Provincia</th>
                <td>{{ user.provincia }}</td>
            </tr>
            <tr>
                <th>Ciudad</th>
                <td>{{ user.ciudad }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('user_index') }}">back to list</a>

    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

templates/user/user_orders.html.twig
{% include 'navbar.html.twig' %}

{% block stylesheets %}
    <link href="{{ asset('assets/css/orders-detail.css') }}" type="text/css" rel="stylesheet" />
    <style>

        .search-button {

            height: 40px;
        }
    </style>
{% endblock %}
{% block body %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <div  class="main-container">
<table class="table">
    <thead>
    <tr>
        <th>Nº Pedido</th>
        <th>Creado</th>

        <th>Total</th>

    </tr>
    </thead>
    <tbody>
    {% for orders in order %}
        <tr>
            <td>Nº {{ orders.id }}</td>
            <td>{{ orders.createdAt ? orders.createdAt|date('Y-m-d') : '' }}</td>


            <td>{{ orders.getTotal() }} €</td>
            <td><button class="btn-more"><a href="{{ path('order_details', {'id': orders.id}) }}">Detalles</a></button></td>
            <td><button class="btn-more"><a href="{{ path('generar_pdf', {'id': orders.id}) }}">Generar PDF</a></button></td>
        </tr>

    {% else %}
        <tr>
            <td colspan="12">no records found</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
    </div>
{% endblock %}
{% include 'footer.html.twig' %}